config/routes.rb
# Routing configuration
Lines::Application.routes.draw do

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'tags/:tag', to: 'articles#index', as: :tag

  resources :sessions

  resources :articles, only: [:index, :show] do
    get 'page/:page', action: :index, on: :collection
  end

  resources :short_articles, only: [:index, :show], controller: :articles do
    get 'page/:page', action: :index, on: :collection
  end

  # Admin namespace
  namespace :admin do
    resources :articles do
      get :autocomplete_tag_name, on: :collection
      post :toggle_publish
      post :toggle_feature
    end
    resources :authors
    resources :pictures, only: [:create, :update, :destroy]
    resources :users
    root :to => 'articles#index'
  end
  
  root :to => 'articles#index'

end

app/models/article.rb
# {Article}s are the core of the lines blog. 
# 
# An {Article} must have on or more {Author}s through {Authorable}.
# 
# An article extends FriendlyId to provide meaningful slugs instead of the usual id value. 
# 
# Slugs are unique and contain the article's title. A incremental numerical value
# is added to the slug title if the it already exists in the database.
class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  # Relations
  has_many :pictures
  has_many :authorables
  has_many :authors, through: :authorables

  attr_accessor :hero_image_file
  accepts_nested_attributes_for :pictures, :authors


  # Mount Carrierwave uploaders
  mount_uploader :hero_image, HeroImageUploader
  mount_uploader :document, DocumentUploader

  # Pagination and tagging
  paginates_per CONFIG[:articles_per_page]
  acts_as_taggable

  # Validations
  validates :title, :content, :author_ids, :published_at, presence: true
  validate :one_image_selected

  # Callbacks
  after_save :update_used_images, :refresh_sitemap

  # Model Scopes
  scope :published, -> { where(published: true).order("featured DESC, published_at DESC") }

  # Predifined hero images.
  # Images are loaded from the <tt>public/heroes</tt> directory
  HERO_IMAGES = %w(001_dark.jpg 001.jpg 002_dark.jpg 002.jpg 003_dark.jpg 003.jpg)

  # Returns URL of selected image from HERO_IMAGES array
  def short_hero_image_url
    "#{self.short_hero_image}"
  end

  # Returns array of images used in content
  def used_images
    result = content.scan(/!\[.*\]\(.*\/image\/(\d.*)\/.*\)/)
    image_ids = result.nil? ? nil : result.map{ |i| i[0].to_i }.uniq
    image_ids
  end

  # Returns the url for the hero image
  def image_url
    self.hero_image? ? self.hero_image_url : self.short_hero_image
  end

  # Returns value of subtitle
  def sub_title
    read_attribute(:sub_title) || ''
  end

private

  # Finds images used in an articles content and associates each
  # image to the blog article
  def update_used_images
    ActionController::Base.new.expire_fragment(self)
    image_ids = self.used_images
    if !image_ids.nil?
      Picture.where(id: image_ids).each do |picture|
        picture.update_attributes(article_id: self.id)
      end
    end
  end

  # Refreshes the sitemap and pings the search engines
  def refresh_sitemap
    if self.published
      if Rails.env == 'production'
        SitemapGenerator::Interpreter.run(config_file: ENV["CONFIG_FILE"])
        SitemapGenerator::Sitemap.ping_search_engines 
      end
    end
  end

  # Validates if either a predefined hero image is selected or a custom hero
  # image uploaded. 
  def one_image_selected
    if both_images_selected || no_image_selected
      errors[:base] << 'You have to either select an image or upload one.'
    end
  end

  # Returns true if both a hero image is uploaded and a predefined hero image is selected
  def both_images_selected
    hero_image.present? && short_hero_image.present?
  end

  # Returns false if no hero image is selected or uploaded
  def no_image_selected
    !hero_image.present? && !short_hero_image.present?
  end

end

app/controllers/admin/articles_controller.rb
# Provides the CRUD operations for +Article+.
# Also handles base64 encoded file uploads and toggling of 
# published and featured state of an +Article+
# 
# Inherits from +Admin::ApplicationController+ to ensure authentication.
class Admin::ArticlesController < Admin::ApplicationController

  autocomplete :tag, :name, class_name: 'ActsAsTaggableOn::Tag'
  before_action :process_base64_upload, only: [:create, :update]

  # Lists all articles. Provides <tt>@articles_unpublished</tt> and 
  # <tt>@articles_published</tt> to distinguish between published and
  # unpublished articles
  def index
    @articles = Article.order('published ASC, featured DESC, published_at DESC').page(params[:page]).per(25)
    @articles_unpublished = @articles.select{|a| a.published == false}
    @articles_published = @articles.select{|a| a.published == true}
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /admin/articles/1
  def show
    @article = Article.find(params[:id])
    @first_page = true

    respond_to do |format|
      format.html {render :show, layout: 'application'}
    end
  end

  # GET /admin/articles/new
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /admin/articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /admin/articles
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to admin_article_path(@article), notice: 'Article was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /admin/articles/1
  # TODO: Very much is happening here. Move deletion of hero_image to the article model
  def update
    @article = Article.find(params[:id])
    a_params = article_params

    # replace picture_path with the new uploaded file
    a_params[:hero_image] = @uploaded_file if @uploaded_file

    # delete uploaded hero image when predifined image is selected
    if !a_params[:hero_image_cache].present? && a_params[:short_hero_image].present?
      @article.remove_hero_image! 
      @article.remove_hero_image = true 
      @article.save
    end

    respond_to do |format|
      if @article.update_attributes(article_params)
        ActionController::Base.new.expire_fragment(@article)
        format.html { redirect_to admin_article_path(@article), notice: 'Article was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /admin/articles/1
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to admin_articles_url }
    end
  end

  # Toggles published state of an article
  def toggle_publish
    @article = Article.find(params[:article_id])
    @article.update_attributes(published: !@article.published)
    redirect_to admin_articles_url, notice: 'Article updated!'
  end

  # Toggles featured state of an article
  def toggle_feature
    @article = Article.find(params[:article_id])
    old_featured = Article.where(featured: true)
    if old_featured.size > 0
      old_featured.each do |article|
        article.update_attributes(featured: false)
      end
    end
    @article.update_attributes(featured: !@article.featured)
    redirect_to admin_articles_url, notice: 'Article updated!'
  end

  # Handles base64 encoded file uploads
  def process_base64_upload
    @uploaded_file = nil
    #check if file is given
    if params[:article][:hero_image_file] != ""

      picture_filename = "hero_image"
      picture_original_filename = "hero_image"
      picture_content_type = splitBase64(params[:article][:hero_image_file])[:type]
      picture_data = splitBase64(params[:article][:hero_image_file])[:data]

      #create a new tempfile named fileupload
      tempfile = Tempfile.new("fileupload")
      tempfile.binmode

      #get the file and decode it with base64 then write it to the tempfile
      tempfile.write(Base64.decode64(picture_data))

      #create a new uploaded file
      @uploaded_file = ActionDispatch::Http::UploadedFile.new(
        tempfile: tempfile, 
        filename: picture_filename,
        original_filename: picture_original_filename
      )
      @uploaded_file.content_type = picture_content_type
    end
  end

  def splitBase64(uri)
    if uri.match(%r{^data:(.*?);(.*?),(.*)$})
      return {
        type:      $1, # "image/png"
        encoder:   $2, # "base64"
        data:      $3, # data string
        extension: $1.split('/')[1] # "png"
        }
    end
  end

  private

    # Allowed attribute with strong_params
    def article_params
      params.require(:article).permit(:content, :hero_image, :short_hero_image, :published, :published_at, 
        :sub_title, :title, :pictures, :author_ids, :hero_image_cache, :tag_list, :gplus_url, :featured, 
        :document, :document_cache, :hero_image_file, :remove_document, :pictures, :authors,
        pictures_attributes: [:id, :image, :name, :article_id], author_ids: [] )
    end

end

app/controllers/articles_controller.rb
# Lists all Articles and shows specific ones.
# Responds either to HTML and ATOM requests.
class ArticlesController < ApplicationController

  layout 'application'

  KEYWORDS = CONFIG[:keywords]
  SITE_TITLE = CONFIG[:title]

  # Lists all published articles.
  # Responds to html and atom
  def index
    respond_to do |format|
      format.html {
        @first_page = (params[:page] and params[:page].to_i > 0) ? false : true
        if params[:tag]
          @articles = Article.published.tagged_with(params[:tag]).page(params[:page].to_i)
        else
          @articles = Article.published.page(params[:page].to_i).padding(1)
        end
        @first_article = Article.published.first if @articles.first_page?
        set_meta_tags title: SITE_TITLE,
                      description: CONFIG[:meta_description],
                      keywords: KEYWORDS,
                      open_graph: { title: SITE_TITLE,
                                      type: 'website',
                                      url: 'meta_og_url',
                                      site_name: SITE_TITLE,
                                      image: CONFIG[:og_logo]
                                    }

      }
      format.atom{
        @articles = Article.published
      }
    end
  end

  # Shows specific article
  def show
    @first_page = true
    @article = Article.published.find(params[:id])
    set_meta_tags title: @article.title,
                  keywords: KEYWORDS + @article.tag_list.to_s,
                  open_graph: { title: SITE_TITLE,
                                   type: 'article',
                                   url: 'meta_og_url',
                                   site_name: SITE_TITLE,
                                   image: CONFIG[:host] + @article.image_url
                                 }
    if request.path != article_path(@article)
      return redirect_to @article, status: :moved_permanently
    end
  end

end

app/views/admin/articles/_form.html.erb
<%= simple_form_for([:admin, @article], id: 'article_form') do |f| %>

  <div class="new-article">
    <div class="row">
      <div class="label">
        <h3><%= f.label :hero_image, "Hero Image" %> <span class="required">*</span></h3>
      </div>
      <div class="input">
        <div class="hero-image" style="background: url('<%= @article.hero_image? ? @article.hero_image : @article.short_hero_image %>'); background-size: cover;">
          <% if @article.hero_image? %>
            <%= f.label :hero_image, "Change Image", class: "choose-file" %>
          <% elsif @article.short_hero_image? %>
            <%= f.label :hero_image, "Change Image", class: "choose-file" %>
          <% else %>
            <%= f.label :hero_image, "Upload Image", class: "choose-file" %>
          <% end %>
          <%= f.file_field :hero_image, class: "hero-image-value" %>
          <%= f.hidden_field :hero_image_file %>
          <div class="hidden">
            <%= f.hidden_field :hero_image_cache, class: "hero-image-cache" %>
            <span id="hero_image_name"><%= (@article.hero_image.filename) if @article.hero_image? %></span>
          </div>
        </div>
      </div>
      <div class="additional">
        <div class="short-hero-images-box">
          <h2>Default images</h2>
          <div class="short-hero-images">
            <% Article::HERO_IMAGES.each_with_index do |h, i| %>
              <div class="short-hero-image-box">
                <img src="<%= "/heroes/#{h}" %>" width="115" id="hero_<%= i %>" class="select_image <%= 'selected_image' if ('/heroes/' + h) == @article.short_hero_image %>" />
              </div>
            <% end %>
            <%= f.hidden_field :short_hero_image, class: "short-hero-image-cache" %>
          </div>
          <br style="clear: both;" />
        </div>
      </div>
    </div>

    <div class="row">
      <div class="label">
        <h3><%= f.label :title, "Title" %> <span class="required">*</span></h3>
      </div>
      <div class="input input-text">
        <%= f.text_field :title, class: "article-title" %>
      </div>
      <div class="additional">

      </div>
    </div>

    <div class="row">
      <div class="label">
        <h3><%= f.label :sub_title, "Subtitle" %></h3>
      </div>
      <div class="input input-text">
        <%= f.text_field :sub_title, class: "article-subtitle" %>
      </div>
      <div class="additional">

      </div>
    </div>

    <div class="row">
      <div class="label">
        <h3><%= f.label :content, "Content" %> <span class="required">*</span></h3>
      </div>
      <div class="input input-textarea">
        <%= f.text_area :content %>
      </div>
      <div class="additional">
        <a href="#formatting_guide" data-toggle="modal" class="btn-formatting-help">&lt;/&gt; Formatting Help</a>
      </div>
    </div>

    <div class="row">
      <div class="label">
        <h3>Authors <span class="required">*</span></h3>
      </div>
      <div class="input">
        <%= hidden_field_tag "article[author_ids][]", nil %>
        <% @author_count = 1 %>
        <% Author.all.each do |author| %>
          <% if (@author_count <= 2) %>
            <div class="checkbox first-row">
          <% else %>
            <div class="checkbox">
          <% end %>
            <%= check_box_tag "article[author_ids][]", author.id, @article.author_ids.include?(author.id), id: dom_id(author) %>
            <label for="<%= dom_id(author) %>" class="checkbox"><span></span><%= author.name %></label>
          </div>
          <% @author_count += 1 %>
        <% end %>
      </div>
      <div class="additional">
        <%= link_to "+ Add new author", new_admin_author_path(), class: "add-new-author" %>
      </div>
    </div>

    <hr />

    <div class="row">
      <div class="label">
        <h3><%= f.label :gplus_url, "G+ URL" %></h3>
      </div>
      <div class="input input-text">
        <%= f.text_field :gplus_url %>
      </div>
      <div class="additional">

      </div>
    </div>

    <div class="row">
      <div class="label">
        <h3><label>Document</label></h3>
      </div>
      <div class="input">
        <div class="documents">
          <%= f.label :document, "#{@article.document? ? @article.document.file.filename : 'Choose File' }", class: "choose-files" -%>
          <%= f.file_field :document, class: "article-document-value" %>
          <div class="hidden">
            <%= f.hidden_field :document_cache %>
            <%= (@article.hero_image.filename) if @article.document? %>
          </div>
        </div>

        <% if @article.document? %>
        <div class="checkbox">
          <%= f.check_box :remove_document %>
          <label for="article_remove_document" class="checkbox"><span></span>Delete document</label>
        </div>
        <% end %>

      </div>
      <div class="additional">

      </div>
    </div>

    <div class="row">
      <div class="label">
        <h3><%= f.label :tag_list, "Tags" %></h3>
      </div>
      <div class="input input-text">
        <%= f.autocomplete_field :tag_list, autocomplete_tag_name_admin_articles_path, :"data-delimiter" => ', ' %>
      </div>
      <div class="additional">

      </div>
    </div>

    <div class="row">
      <div class="label">
        <h3>Published at <span class="required">*</span></h3>
      </div>
      <div class="input input-text">
        <%= f.text_field :published_at, value: (@article.published_at || Time.now).strftime("%Y-%m-%d"), 'data-behaviour' => 'datepicker' %>
      </div>
      <div class="additional">

      </div>
    </div>

    <%= render_navbar do %>
      <%= f.submit "Save Article", class: "btn btn-save-publish" %>
      <%= link_to "Cancel", admin_articles_path, class: "btn btn-cancel" %>
    <% end %>        

  </div>
<% end %>

<%= render 'admin/articles/formatting_guide' %>

app/views/admin/articles/_formatting_guide.html.erb
<div id="formatting_guide" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="formatting_guide_inner">
    <div class="modal-header">
      <button type="button" class="btn btn-close-formatting-small" data-dismiss="modal" aria-hidden="true">×</button>
      <h2>Formatting Guid &mdash; Markdown Cheat Sheet</h2>
      <hr />
    </div>
    <div class="modal-body">
      <div class="content cheatsheet">
        <div class="cheatsheet-content">
          <div class="mod">
            <div class="col">
              <h2>Format Text</h2>
              <p><strong>Headers</strong></p>
              <pre># This is an &lt;h1&gt; tag
## This is an &lt;h2&gt; tag
###### This is an &lt;h6&gt; tag</pre>
              <p><strong>Text styles</strong></p>
              <pre>*This text will be italic*
_This will also be italic_
**This text will be bold**
__This will also be bold__

*You **can** combine them*</pre>
            </div>
            <div class="col">
              <h2>Lists</h2>
              <p><strong>Unordered</strong></p>
              <pre>* Item 1
* Item 2
  * Item 2a
  * Item 2b</pre>
              <p><strong>Ordered</strong></p>
              <pre>1. Item 1
2. Item 2
3. Item 3
   * Item 3a
   * Item 3b</pre>
            </div>
            <div class="col">
              <h2>Miscellaneous</h2>
              <p><strong>Images</strong></p>
              <pre>![GitHub Logo](/images/logo.png)
Format: ![Alt Text](url)</pre>
              <p><strong>Links</strong></p>
              <pre>http://github.com - automatic!
[GitHub](http://github.com)</pre>
              <p><strong>Blockquotes</strong></p>
              <pre>As Kanye West said:

&gt; We're living the future so
&gt; the present is our past.</pre>
            </div>
          </div>
          <div class="rule"></div>

          <h2>Code Examples in Markdown</h2>
          <div class="col">
            <pre>```javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```</pre>
            </div>
            <div class="col">
              <p><strong>Or, indent your code 4 spaces</strong></p>
              <pre>Here is a Python code example
without syntax highlighting:

  def foo:
    if not bar:
      return true</pre>
            </div>
            <div class="col">
              <p><strong>Inline code for comments</strong></p>
              <pre>I think you should use an
`&lt;addr&gt;` element here instead.</pre>
            </div>
        </div>

        </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-close-formatting" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </div>
</div>

app/views/admin/articles/_picture_box.html.erb
<div class="well well_small">
  
  <h2>Upload photos</h2>

  <div id="pictures">
    <% if @article.pictures.any? %>
      <% @article.pictures.each do |picture| %>
        <div class="picture-preview" id="<%= dom_id picture %>">
          <div class="picture"><%= image_tag picture.image_url(:preview) %></div>
          <a href="#insert" class="insert-image" data-url="<%= picture.image_url %>"></a>
          <%= button_to "", admin_picture_path(picture), remote: true, confirm: "Are you sure?", method: :delete, class: 'btn-delete-photo' %>
        </div>
      <% end %>
    <% end %>
  </div>
  
  <div class="picture-preview">
    <%= form_for [:admin, Picture.new], {enctype: "multipart/form-data"} do |f| %>
      <img src="/assets/ic_action_add.png" style="height: 48px; width: 48px; padding: 18px;" alt="" />
      <input id="picture_image" multiple="multiple" name="picture[image]" type="file" />
    <% end %>
  </div>
  <br style="clear: both;" />

</div>

<script id="template-upload" type="text/x-tmpl">
  <div class="upload">
    <div class="progress"><div class="bar" style="width: 0%"></div></div>
  </div>
</script>

app/views/admin/articles/edit.html.erb
<% if @article.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

  <ul>
  <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
  <a href="#" class="close">x</a>
</div>
<% end %>

<div class="row">
  <div class="span8">
    <div class="form-box">
      <%= render 'admin/articles/form' %>
    </div>
  </div>

  <div class="span4 picture-box">
    <%= render 'admin/articles/picture_box' %>
  </div>

</div>

app/views/admin/articles/index.html.erb
<%= render_navbar do %>
  <%= link_to 'New Article', new_admin_article_path, class: "btn btn-new-article" %>  
  <%= link_to 'Authors', admin_authors_path, class: "btn btn-authors" %>
  <%= link_to 'Visit Blog', "/", class: "btn btn-view-blog" %>
<% end %>

<% if @articles_unpublished.size > 0 %>
  <h2>Unpublished articles</h2>
  <div class="articles-list">
    <% @articles_unpublished.each do |article| %>
      <table class="article unpublished" cellspacing="0" cellpadding="0">
        <tr>
          <td class="preview"><%= link_to "", admin_article_path(article), title: "Preview article" %></td>
          <td style="width: 2px;"></td>
          <td class="edit"><%= link_to "", edit_admin_article_path(article), title: "Edit article" %></td>
          <td class="title"><%= link_to truncate(article.title, length: 25, omission: "…"), edit_admin_article_path(article), title: article.title %></td>
          <td class="subtitle"><%= link_to truncate(article.sub_title, length: 35, omission: "…"), edit_admin_article_path(article), title: article.sub_title %></td>
          <td class="date"><%= article.published_at.to_date %></td>
          <td class="delete"><%= button_to "", {controller: :articles, action: 'destroy', id: article.id }, method: :delete, confirm: "Are you sure?" %></td>
        </tr>
      </table>
    <% end %>
  </div>
<% end %>

<% if @articles_published.size > 0 %>
  <h2>Published articles</h2>
  <div class="articles-list">
    <% @articles_published.each do |article| %>
      <table class="article published" cellspacing="0" cellpadding="0">
        <tr>
          <td class="preview"><%= link_to "", admin_article_path(article), title: "Preview article" %></td>
          <td style="width: 2px;"></td>
          <td class="edit"><%= link_to "", edit_admin_article_path(article), title: "Edit article" %></td>
          <td class="title"><%= link_to truncate(article.title, length: 25, omission: "…"), edit_admin_article_path(article), title: article.title %></td>
          <td class="subtitle"><%= link_to truncate(article.sub_title, length: 35, omission: "…"), edit_admin_article_path(article), title: article.sub_title %></td>
          <td class="featured <%= article.featured ? '' : 'not' %>"><%= button_to "", admin_article_toggle_feature_path(article) %></td>
          <td class="date"><%= article.published_at.to_date %></td>
          <td class="delete"><%= button_to "", {controller: :articles, action: 'destroy', id: article.id }, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      </table>
    <% end %>
  </div>
<% end %>

<% if @articles_unpublished.size == 0 && @articles_published.size == 0 %>
  <h2>There are no articles yet</h2>
<% else %>
  <%= paginate @articles %>

  <div class="top_link" onclick="$(document).scrollTop();"></div>
<% end %>

app/views/admin/articles/new.html.erb
<%= content_for :admin_nav do %>
  <%= link_to 'New Article', new_admin_article_path, class: "btn btn-new-article" %>
<% end %>


<% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    <a href="#" class="close">x</a>
  </div>
<% end %>

<div class="row">
  <div class="span8">
    <div class="form-box">
      <%= render 'admin/articles/form' %>
    </div>
  </div>
  <div class="span4 picture-box">
    <%= render 'admin/articles/picture_box' %>
  </div>
</div>

app/views/admin/articles/show.html.erb
<%= render_navbar do %>
  <%= link_to 'Edit', edit_admin_article_path(@article), :class => "btn btn-edit" %>
  <%= button_to (@article.published ? "Unpublish" : "Publish"), admin_article_toggle_publish_path(@article), :class => "btn btn-publish" %>
<% end %>

<%= render "articles/article", :article_counter => -1, :article => @article %>