config/routes.rb
# Routing configuration
Lines::Application.routes.draw do

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'tags/:tag', to: 'articles#index', as: :tag

  resources :sessions

  resources :articles, only: [:index, :show] do
    get 'page/:page', action: :index, on: :collection
  end

  resources :short_articles, only: [:index, :show], controller: :articles do
    get 'page/:page', action: :index, on: :collection
  end

  # Admin namespace
  namespace :admin do
    resources :articles do
      get :autocomplete_tag_name, on: :collection
      post :toggle_publish
      post :toggle_feature
    end
    resources :authors
    resources :pictures, only: [:create, :update, :destroy]
    resources :users
    root :to => 'articles#index'
  end
  
  root :to => 'articles#index'

end

app/models/author.rb
# Each {Article} must have one or more {Author}s. 
# 
# An {Author} is unrelated to the currently logged in user. This allows to publish
# {Article}s by guest authors that don't need an own user account
class Author < ActiveRecord::Base
    
  # Relations
  has_many :authorables
  has_many :articles, through: :authorables
  
  # Validations
  validates :name, :email, :description, presence: true

  # Callbacks
  before_destroy :check_for_articles

  # Returns the first name 
  def first_name
  	self.name.split(" ").first
  end

  # Returns the last name
  def last_name
  	self.name.split(" ").last
  end

  private

    # Return false if an author has associated articles. 
    # This check is called before destroying an author to prevent leaving articles
    # without an associated author.
    def check_for_articles
      if articles.count > 0
        errors[:base] << "cannot delete author with existing blog articles"
        return false
      end
    end
end

app/controllers/admin/authors_controller.rb
# Provides CRUD actions for +Author+ model.
class Admin::AuthorsController < Admin::ApplicationController

  before_action :author_params

  # Listes all authroes
  def index
    @authors = Author.all
  end

  # Shows an author
  def show
    @author = Author.find(params[:id])
  end

  # New author
  def new
    @author = Author.new
  end

  # Edit an existing author
  def edit
    @author = Author.find(params[:id])
  end

  # Create a new author from params
  def create
    @author = Author.new(params[:author])

    if @author.save
      redirect_to admin_author_path @author, notice: 'Author was successfully created.'
    else
      render action: "new"
    end
  end

  # Update an existing author from params
  def update
    @author = Author.find(params[:id])

    if @author.update_attributes(params[:author])
      redirect_to admin_author_path @author, notice: 'Author was successfully updated.'
    else
      render action: "edit"
    end
  end

  # Delete an author
  def destroy
    @author = Author.find(params[:id])
    if @author.destroy
      redirect_to admin_authors_url
    else
      @authors = Author.all
      render "index" 
    end
  end

  private

    # Use strong_params
    def author_params
      params.require(:author).permit(:email, :name, :description, :gplus_profile)
    end
end

app/views/admin/authors/_form.html.erb
<%= simple_form_for([:admin, @author]) do |f| %>
  <div class="new-author">
    <div class="row">
      <div class="label">
        <h3>
          <%= f.label :name, "Name" %>
        </h3>
      </div>
      <div class="input">
        <%= f.text_field :name %>
      </div>
      <div class="additional"></div>
    </div>
    <div class="row">
      <div class="label">
        <h3>
          <%= f.label :email, "E-Mail" %>
        </h3>
      </div>
      <div class="input">
        <%= f.text_field :email %>
      </div>
      <div class="additional"></div>
    </div>
    <div class="row">
      <div class="label">
        <h3>
          <%= f.label :gplus_profile, "G+ Profile" %>
        </h3>
      </div>
      <div class="input">
        <%= f.text_field :gplus_profile %>
      </div>
      <div class="additional"></div>
    </div>
    <div class="row">
      <div class="label">
        <h3>
          <%= f.label :description, "Description" %>
        </h3>
      </div>
      <div class="input">
        <%= f.text_area :description %>
      </div>
      <div class="additional"></div>
    </div>

    <%= render_navbar do %>
      <%= f.submit "Save Author", class: "btn btn-save-publish" %>
      <%= link_to 'Cancel', admin_authors_path, class: 'btn btn-cancel' %>
    <% end %>  

  </div>
<% end %>

app/views/admin/authors/edit.html.erb
<% if @author.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

  <ul>
  <% @author.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
  <a href="#" class="close">x</a>
</div>
<% end %>

<div class="row">
  <div class="span8">
    <div class="form-box">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/authors/index.html.erb
<%= render_navbar do %>
  <%= link_to 'New Author', new_admin_author_path, class: "btn btn-new-author" %>
  <%= link_to 'Articles', admin_articles_path, class: "btn btn-articles" %>
  <%= link_to 'Visit Blog', "/", class: "btn btn-view-blog" %>
<% end %>

<% if defined?(@author) && @author.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

  <ul>
  <% @author.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
  <a href="#" class="close">x</a>
</div>
<% end %>

<h2>All authors</h2>
<div class="authors-list">
  <% @authors.each do |author| %>
    <table class="author">
      <tr>
        <td class="show"><%= link_to '', admin_author_path(author) %></td>
        <td class="edit"><%= link_to '', edit_admin_author_path(author) %></td>
        <td class="name"><%= link_to author.name, edit_admin_author_path(author) %></td>
        <td class="email"><%= author.email %></td>
        <td class="delete"><%= link_to '', admin_author_path(author), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td class="delete"><%= button_to "", {controller: :authors, action: 'destroy', id: author.id }, method: :delete, confirm: "Are you sure?" %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/admin/authors/new.html.erb
<% if @author.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

    <ul>
    <% @author.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    <a href="#" class="close">x</a>
  </div>
<% end %>

<div class="row">
  <div class="span8">
    <div class="form-box">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/authors/show.html.erb
<div class="new-author">
  <div class="row show">
    <div class="label">
      <h3>
        Name
      </h3>
    </div>
    <div class="input">
      <%= @author.name %>
    </div>
    <div class="additional"></div>
  </div>
  <div class="row show">
    <div class="label">
      <h3>
        E-Mail
      </h3>
    </div>
    <div class="input">
      <%= @author.email %>
    </div>
    <div class="additional"></div>
  </div>
  <div class="row show">
    <div class="label">
      <h3>
        G+ Profile
      </h3>
    </div>
    <div class="input">
      <%= link_to @author.gplus_profile, @author.gplus_profile %>
    </div>
    <div class="additional"></div>
  </div>
  <div class="row show">
    <div class="label">
      <h3>
        Description
      </h3>
    </div>
    <div class="input">
      <%= @author.description %>
    </div>
    <div class="additional"></div>
  </div>
  <br />
  <br />
  <br />
  <%= render_navbar do %>
    <%= link_to 'Edit', edit_admin_author_path(@author), class: "btn btn-save-publish" %>
    <%= link_to 'Back', admin_authors_path, class: "btn btn-cancel" %>
  <% end %>
</div>